import type { Author, Category, JournalPost } from "../types";

// TEMPORARY sample content, same convention as ./data.ts and
// ./portfolioData.ts: every record is clearly [SAMPLE]-labeled and exists
// only to build and review the Journal end-to-end. Must be replaced with
// real, approved content (or removed) before launch.

export const JOURNAL_CATEGORIES: Category[] = [
  { id: "jcat-articles", slug: "articles", name: "Articles", description: "General long-form articles." },
  { id: "jcat-tutorials", slug: "tutorials", name: "Tutorials", description: "Step-by-step, how-to content." },
  { id: "jcat-bts", slug: "behind-the-scenes", name: "Behind the Scenes", description: "Process and on-set stories." },
  { id: "jcat-photo-tips", slug: "photography-tips", name: "Photography Tips", description: "Practical photography advice." },
  { id: "jcat-business", slug: "business-insights", name: "Business Insights", description: "Running a creative practice." },
  { id: "jcat-faith", slug: "faith-leadership", name: "Faith & Leadership", description: "Faith and leadership reflections." },
  { id: "jcat-travel", slug: "travel", name: "Travel", description: "Location and travel-shoot stories." },
  { id: "jcat-workshop-recaps", slug: "workshop-recaps", name: "Workshop Recaps", description: "Recaps of past Ordift Academy workshops." },
  { id: "jcat-client-stories", slug: "client-stories", name: "Client Stories", description: "Stories from client collaborations." },
  { id: "jcat-case-studies", slug: "case-studies", name: "Case Studies", description: "In-depth project breakdowns." },
  { id: "jcat-announcements", slug: "announcements", name: "Announcements", description: "Studio announcements." },
  { id: "jcat-news", slug: "news", name: "News", description: "Industry and studio news." },
  { id: "jcat-video", slug: "video-articles", name: "Video Articles", description: "Video-led editorial content." },
];

export const AUTHORS: Author[] = [
  {
    id: "author-sample-1",
    slug: "sample-editorial-team",
    name: "[SAMPLE] Ordift Editorial Team",
    title: "[SAMPLE] Contributor",
    bio: "Placeholder author profile for architecture review only. Real author profiles, reflecting the team of creative minds behind Ordift Studios, will replace this before launch.",
    photoUrl: null,
    isPlaceholder: true,
  },
  {
    id: "author-sample-2",
    slug: "sample-guest-contributor",
    name: "[SAMPLE] Guest Contributor",
    title: "[SAMPLE] Guest Writer",
    bio: "Placeholder author profile demonstrating multiple author support.",
    photoUrl: null,
    isPlaceholder: true,
  },
];

const inFourteenDays = new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString();
const tenDaysAgo = new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString();
const fortyDaysAgo = new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString();

export const JOURNAL_POSTS: JournalPost[] = [
  {
    id: "journal-sample-1",
    slug: "sample-five-lighting-setups",
    title: "[SAMPLE] Five Lighting Setups Every Photographer Should Know",
    status: "published",
    featured: true,
    format: "written",
    authorId: "author-sample-1",
    categoryIds: ["jcat-photo-tips", "jcat-tutorials"],
    tags: ["lighting", "studio", "gear"],
    heroImage: { url: "", type: "image", alt: "[SAMPLE] Studio lighting setup" },
    videoUrl: null,
    excerpt: "Placeholder excerpt for architecture review only — a short summary of five studio lighting setups.",
    body: "This is placeholder article copy for architecture review only. Real editorial content, written and approved by Ordift Studios, will replace this before launch. ".repeat(40),
    publishedAt: tenDaysAgo,
    scheduledFor: null,
    relatedPostIds: ["journal-sample-2"],
    relatedProjectIds: ["portfolio-sample-1"],
    relatedWorkshopIds: ["sample-workshop-1"],
    newsletterExcerpt: "[SAMPLE] Newsletter-formatted blurb, pending real copy.",
    seo: { metaTitle: null, metaDescription: null, ogImageUrl: null, canonicalUrl: null },
  },
  {
    id: "journal-sample-2",
    slug: "sample-behind-the-scenes-heritage-film",
    title: "[SAMPLE] Behind the Scenes: Heritage Brand Film Shoot",
    status: "published",
    featured: true,
    format: "written",
    authorId: "author-sample-1",
    categoryIds: ["jcat-bts", "jcat-case-studies"],
    tags: ["videography", "process"],
    heroImage: { url: "", type: "image", alt: "[SAMPLE] On-set behind-the-scenes photo" },
    videoUrl: null,
    excerpt: "Placeholder excerpt for architecture review only — a look at how a brand film comes together.",
    body: "This is placeholder article copy for architecture review only, demonstrating a Journal post cross-linked to a Portfolio case study. ".repeat(30),
    publishedAt: tenDaysAgo,
    scheduledFor: null,
    relatedPostIds: [],
    relatedProjectIds: ["portfolio-sample-2"],
    relatedWorkshopIds: [],
    newsletterExcerpt: null,
    seo: { metaTitle: null, metaDescription: null, ogImageUrl: null, canonicalUrl: null },
  },
  {
    id: "journal-sample-3",
    slug: "sample-first-workshop-recap",
    title: "[SAMPLE] What We Learned Running Our First Workshop",
    status: "published",
    featured: false,
    format: "written",
    authorId: "author-sample-2",
    categoryIds: ["jcat-workshop-recaps", "jcat-business"],
    tags: ["academy", "teaching"],
    heroImage: { url: "", type: "image", alt: "[SAMPLE] Workshop classroom photo" },
    videoUrl: null,
    excerpt: "Placeholder excerpt for architecture review only — reflections after a first workshop.",
    body: "This is placeholder article copy for architecture review only, cross-linked to a Workshop Platform entry. ".repeat(30),
    publishedAt: fortyDaysAgo,
    scheduledFor: null,
    relatedPostIds: [],
    relatedProjectIds: [],
    relatedWorkshopIds: ["sample-workshop-1"],
    newsletterExcerpt: null,
    seo: { metaTitle: null, metaDescription: null, ogImageUrl: null, canonicalUrl: null },
  },
  {
    id: "journal-sample-4",
    slug: "sample-faith-discipline-creative-process",
    title: "[SAMPLE] Faith, Discipline and the Creative Process",
    status: "published",
    featured: false,
    format: "written",
    authorId: "author-sample-1",
    categoryIds: ["jcat-faith"],
    tags: ["faith", "discipline"],
    heroImage: { url: "", type: "image", alt: "[SAMPLE] Reflective editorial image" },
    videoUrl: null,
    excerpt: "Placeholder excerpt for architecture review only.",
    body: "This is placeholder article copy for architecture review only. Real reflections, written and approved by Ordift Studios, will replace this before launch. ".repeat(30),
    publishedAt: fortyDaysAgo,
    scheduledFor: null,
    relatedPostIds: [],
    relatedProjectIds: [],
    relatedWorkshopIds: [],
    newsletterExcerpt: null,
    seo: { metaTitle: null, metaDescription: null, ogImageUrl: null, canonicalUrl: null },
  },
  {
    id: "journal-sample-5",
    slug: "sample-a-day-in-the-studio",
    title: "[SAMPLE] A Day in the Studio",
    status: "published",
    featured: false,
    format: "video",
    authorId: "author-sample-2",
    categoryIds: ["jcat-video", "jcat-bts"],
    tags: ["studio", "vlog"],
    heroImage: { url: "", type: "video", alt: "[SAMPLE] Studio vlog thumbnail" },
    videoUrl: "https://www.youtube.com/watch?v=sample",
    excerpt: "Placeholder excerpt for architecture review only — a video-led article.",
    body: "This is placeholder video-article copy for architecture review only, demonstrating the video article format.",
    publishedAt: tenDaysAgo,
    scheduledFor: null,
    relatedPostIds: [],
    relatedProjectIds: [],
    relatedWorkshopIds: [],
    newsletterExcerpt: null,
    seo: { metaTitle: null, metaDescription: null, ogImageUrl: null, canonicalUrl: null },
  },
  {
    id: "journal-sample-6",
    slug: "sample-packing-list-location-shoot",
    title: "[SAMPLE] Packing List for a Location Shoot",
    status: "draft",
    featured: false,
    format: "written",
    authorId: "author-sample-1",
    categoryIds: ["jcat-travel", "jcat-tutorials"],
    tags: ["travel", "gear"],
    heroImage: { url: "", type: "image", alt: "[SAMPLE] Packed camera bag" },
    videoUrl: null,
    excerpt: "Placeholder excerpt — this post exists only to verify draft posts are excluded publicly.",
    body: "Draft placeholder body.",
    publishedAt: null,
    scheduledFor: null,
    relatedPostIds: [],
    relatedProjectIds: [],
    relatedWorkshopIds: [],
    newsletterExcerpt: null,
    seo: { metaTitle: null, metaDescription: null, ogImageUrl: null, canonicalUrl: null },
  },
  {
    id: "journal-sample-7",
    slug: "sample-announcing-ordift-workshops",
    title: "[SAMPLE] Announcing Ordift Workshops",
    status: "published",
    featured: false,
    format: "written",
    authorId: "author-sample-1",
    categoryIds: ["jcat-announcements", "jcat-news"],
    tags: ["academy", "announcement"],
    heroImage: { url: "", type: "image", alt: "[SAMPLE] Announcement graphic" },
    videoUrl: null,
    excerpt: "Placeholder excerpt — this post exists only to verify scheduled publishing hides a future-dated post.",
    body: "Scheduled placeholder body.",
    publishedAt: null,
    scheduledFor: inFourteenDays,
    relatedPostIds: [],
    relatedProjectIds: [],
    relatedWorkshopIds: [],
    newsletterExcerpt: null,
    seo: { metaTitle: null, metaDescription: null, ogImageUrl: null, canonicalUrl: null },
  },
];
