import type { Category, Collection, PortfolioProject, Testimonial } from "../types";

// TEMPORARY sample content, same convention as ./data.ts (Workshops):
// every record is clearly [SAMPLE]-labeled and exists only to build and
// review the Portfolio Management System end-to-end. Must be replaced
// with real, approved projects (or removed) before launch — see the
// zero-invention and empty-state rules in ARCHITECTURE.md / CMS_MIGRATION.md.

export const PORTFOLIO_CATEGORIES: Category[] = [
  { id: "pcat-fashion", slug: "fashion", name: "Fashion", description: "Fashion editorial and lookbook work." },
  { id: "pcat-portrait", slug: "portrait", name: "Portrait", description: "Individual and group portraiture." },
  { id: "pcat-corporate", slug: "corporate", name: "Corporate", description: "Corporate and headshot photography." },
  { id: "pcat-product", slug: "product", name: "Product", description: "Product and e-commerce photography." },
  { id: "pcat-food", slug: "food", name: "Food", description: "Food and beverage photography." },
  { id: "pcat-event", slug: "event", name: "Event", description: "Live event coverage." },
  { id: "pcat-commercial", slug: "commercial", name: "Commercial", description: "Commercial and advertising work." },
  { id: "pcat-architecture", slug: "architecture", name: "Architecture", description: "Architectural and interior photography." },
  { id: "pcat-automotive", slug: "automotive", name: "Automotive", description: "Automotive photography." },
  { id: "pcat-campaigns", slug: "campaigns", name: "Campaigns", description: "Multi-discipline brand campaigns." },
  { id: "pcat-bts", slug: "behind-the-scenes", name: "Behind the Scenes", description: "Behind-the-scenes and process-focused features." },
  { id: "pcat-personal", slug: "personal-projects", name: "Personal Projects", description: "Self-directed, non-client work." },
];

// Collections (unordered groupings) and Series (ordered, via isOrdered)
// share one type — see Collection's doc comment in types.ts.
export const PORTFOLIO_COLLECTIONS: Collection[] = [
  {
    id: "pcol-2026-campaigns",
    slug: "2026-campaigns",
    name: "[SAMPLE] 2026 Campaigns",
    description: "Placeholder curated collection grouping this year's campaign work.",
    isOrdered: false,
  },
  {
    id: "pcol-self-portrait-series",
    slug: "studio-self-portrait-series",
    name: "[SAMPLE] Studio Self-Portrait Series",
    description: "Placeholder ordered series — demonstrates Project Series via seriesOrder.",
    isOrdered: true,
  },
];

export const PORTFOLIO_TESTIMONIALS: Testimonial[] = [
  {
    id: "ptestimonial-sample-1",
    quote:
      "[PLACEHOLDER TESTIMONIAL] Sample client quote standing in for a real one, shown only to preview how a project-level testimonial renders.",
    authorName: "[Placeholder Name]",
    authorRole: "[Placeholder — e.g. Creative Director, Client Brand]",
    isPlaceholder: true,
  },
];

export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
  {
    id: "portfolio-sample-1",
    slug: "sample-atelier-fashion-editorial",
    title: "[SAMPLE] Atelier Fashion Editorial",
    status: "published",
    scheduledFor: null,
    featured: true,
    heroMedia: { url: "", type: "image", alt: "[SAMPLE] Fashion editorial hero image" },
    disciplines: ["photography", "content-creation"],
    categoryIds: ["pcat-fashion", "pcat-campaigns"],
    collectionIds: ["pcol-2026-campaigns"],
    seriesOrder: null,
    client: "[SAMPLE] Client Name (placeholder)",
    year: 2026,
    location: "Accra, Ghana",
    servicesProvided: ["[SAMPLE] Art Direction", "[SAMPLE] Photography", "[SAMPLE] Retouching"],
    equipmentUsed: ["[SAMPLE] Camera body", "[SAMPLE] Studio strobes"],
    tags: [],
    collaborators: [
      { id: "collab-1", name: "[SAMPLE] Name", role: "Photographer" },
      { id: "collab-2", name: "[SAMPLE] Name", role: "Stylist" },
      { id: "collab-3", name: "[SAMPLE] Name", role: "Makeup Artist" },
    ],
    story:
      "This is placeholder case-study copy for architecture review only. Real project narratives, written with client permission, will replace this before launch.",
    objective: "[SAMPLE] Placeholder objective statement.",
    strategy: "[SAMPLE] Placeholder creative strategy.",
    challenges: "[SAMPLE] Placeholder description of challenges encountered.",
    solution: "[SAMPLE] Placeholder description of the creative solution.",
    process: "[SAMPLE] Placeholder description of the creative process.",
    deliverables: ["[SAMPLE] 20 final retouched images", "[SAMPLE] 5 social crops"],
    results: "[SAMPLE] Placeholder results/impact statement, pending real data.",
    awards: [{ id: "award-1", title: "[SAMPLE] Award Name", issuer: "[SAMPLE] Issuing Body", year: 2026 }],
    publications: [{ id: "pub-1", name: "[SAMPLE] Publication Name", url: null, year: 2026 }],
    gallery: [],
    behindTheScenesGallery: [],
    beforeAfterGallery: [
      {
        id: "ba-1",
        before: { url: "", type: "image", alt: "[SAMPLE] Before retouching" },
        after: { url: "", type: "image", alt: "[SAMPLE] After retouching" },
        caption: "[SAMPLE] Retouching comparison",
      },
    ],
    videos: [],
    downloadableAssets: [{ id: "dl-1", label: "[SAMPLE] Press Kit", url: "", fileType: "PDF" }],
    testimonialIds: ["ptestimonial-sample-1"],
    relatedProjectIds: ["portfolio-sample-2", "portfolio-sample-4"],
    relatedWorkshopIds: ["sample-workshop-1"],
    isPasswordProtected: false,
    seo: { metaTitle: null, metaDescription: null, ogImageUrl: null, canonicalUrl: null },
  },
  {
    id: "portfolio-sample-2",
    slug: "sample-heritage-brand-film",
    title: "[SAMPLE] Heritage Brand Film",
    status: "published",
    scheduledFor: null,
    featured: true,
    heroMedia: { url: "", type: "video", alt: "[SAMPLE] Brand film hero video" },
    disciplines: ["videography", "branding"],
    categoryIds: ["pcat-commercial", "pcat-campaigns"],
    collectionIds: ["pcol-2026-campaigns"],
    seriesOrder: null,
    client: "[SAMPLE] Client Name (placeholder)",
    year: 2026,
    location: "Kumasi, Ghana",
    servicesProvided: ["[SAMPLE] Creative Direction", "[SAMPLE] Videography", "[SAMPLE] Editing"],
    equipmentUsed: [],
    tags: [],
    collaborators: [
      { id: "collab-4", name: "[SAMPLE] Name", role: "Director" },
      { id: "collab-5", name: "[SAMPLE] Name", role: "Videographer" },
    ],
    story:
      "This is placeholder case-study copy for architecture review only, demonstrating a video-led project with no client name disclosed publicly.",
    objective: "[SAMPLE] Placeholder objective statement.",
    strategy: "[SAMPLE] Placeholder creative strategy.",
    challenges: null,
    solution: null,
    process: "[SAMPLE] Placeholder description of the creative process.",
    deliverables: ["[SAMPLE] 90-second brand film", "[SAMPLE] 3 cutdowns for social"],
    results: null,
    awards: [],
    publications: [],
    gallery: [],
    behindTheScenesGallery: [
      { id: "bts-1", url: "", alt: "[SAMPLE] Behind-the-scenes still", caption: "[SAMPLE] On set" },
    ],
    beforeAfterGallery: [],
    videos: [
      { url: "", type: "video", alt: "[SAMPLE] Full brand film" },
      { url: "https://www.youtube.com/watch?v=sample", type: "embed", alt: "[SAMPLE] YouTube upload" },
    ],
    downloadableAssets: [],
    testimonialIds: [],
    relatedProjectIds: ["portfolio-sample-1"],
    relatedWorkshopIds: [],
    isPasswordProtected: false,
    seo: { metaTitle: null, metaDescription: null, ogImageUrl: null, canonicalUrl: null },
  },
  {
    id: "portfolio-sample-3",
    slug: "sample-artisan-market-branding",
    title: "[SAMPLE] Artisan Market Branding",
    status: "published",
    scheduledFor: null,
    featured: false,
    heroMedia: { url: "", type: "image", alt: "[SAMPLE] Brand identity hero image" },
    disciplines: ["branding", "graphic-design"],
    categoryIds: ["pcat-campaigns"],
    collectionIds: [],
    seriesOrder: null,
    client: null,
    year: 2025,
    location: "Online",
    servicesProvided: ["[SAMPLE] Brand Strategy", "[SAMPLE] Visual Identity", "[SAMPLE] Packaging Design"],
    equipmentUsed: [],
    tags: [],
    collaborators: [{ id: "collab-6", name: "[SAMPLE] Name", role: "Designer" }],
    story: "This is placeholder case-study copy for architecture review only, demonstrating a project with no client name shown at all.",
    objective: null,
    strategy: "[SAMPLE] Placeholder creative strategy.",
    challenges: "[SAMPLE] Placeholder description of challenges encountered.",
    solution: "[SAMPLE] Placeholder description of the creative solution.",
    process: null,
    deliverables: ["[SAMPLE] Logo suite", "[SAMPLE] Packaging system"],
    results: "[SAMPLE] Placeholder results/impact statement.",
    awards: [],
    publications: [],
    gallery: [],
    behindTheScenesGallery: [],
    beforeAfterGallery: [],
    videos: [],
    downloadableAssets: [],
    testimonialIds: [],
    relatedProjectIds: [],
    relatedWorkshopIds: [],
    isPasswordProtected: false,
    seo: { metaTitle: null, metaDescription: null, ogImageUrl: null, canonicalUrl: null },
  },
  {
    id: "portfolio-sample-4",
    slug: "sample-golden-plate-food-story",
    title: "[SAMPLE] Golden Plate Food Story",
    status: "published",
    scheduledFor: null,
    featured: false,
    heroMedia: { url: "", type: "image", alt: "[SAMPLE] Food photography hero image" },
    disciplines: ["photography"],
    categoryIds: ["pcat-food", "pcat-commercial"],
    collectionIds: [],
    seriesOrder: null,
    client: "[SAMPLE] Client Name (placeholder)",
    year: 2025,
    location: "Accra, Ghana",
    servicesProvided: ["[SAMPLE] Food Styling Direction", "[SAMPLE] Photography"],
    equipmentUsed: ["[SAMPLE] Macro lens"],
    tags: [],
    collaborators: [],
    story: "This is placeholder case-study copy for architecture review only.",
    objective: null,
    strategy: null,
    challenges: null,
    solution: null,
    process: null,
    deliverables: ["[SAMPLE] 15 final images"],
    results: null,
    awards: [],
    publications: [],
    gallery: [],
    behindTheScenesGallery: [],
    beforeAfterGallery: [],
    videos: [],
    downloadableAssets: [],
    testimonialIds: [],
    relatedProjectIds: ["portfolio-sample-1"],
    relatedWorkshopIds: [],
    isPasswordProtected: false,
    seo: { metaTitle: null, metaDescription: null, ogImageUrl: null, canonicalUrl: null },
  },
  {
    id: "portfolio-sample-5",
    slug: "sample-studio-self-portrait-series",
    title: "[SAMPLE] Studio Self-Portrait Series — Part 1",
    status: "published",
    scheduledFor: null,
    featured: false,
    heroMedia: { url: "", type: "image", alt: "[SAMPLE] Personal project hero image" },
    disciplines: ["photography"],
    categoryIds: ["pcat-portrait", "pcat-personal"],
    collectionIds: ["pcol-self-portrait-series"],
    seriesOrder: 1,
    client: null,
    year: 2025,
    location: "Accra, Ghana",
    servicesProvided: [],
    equipmentUsed: [],
    tags: [],
    collaborators: [],
    story:
      "This is placeholder case-study copy for architecture review only, demonstrating a personal (non-client) project that is also part of an ordered series.",
    objective: null,
    strategy: null,
    challenges: null,
    solution: null,
    process: null,
    deliverables: [],
    results: null,
    awards: [],
    publications: [],
    gallery: [],
    behindTheScenesGallery: [],
    beforeAfterGallery: [],
    videos: [],
    downloadableAssets: [],
    testimonialIds: [],
    relatedProjectIds: [],
    relatedWorkshopIds: [],
    isPasswordProtected: false,
    seo: { metaTitle: null, metaDescription: null, ogImageUrl: null, canonicalUrl: null },
  },
  {
    id: "portfolio-sample-6",
    slug: "sample-unpublished-draft-project",
    title: "[SAMPLE] Unpublished Draft Project",
    status: "draft",
    scheduledFor: null,
    featured: false,
    heroMedia: { url: "", type: "image", alt: "[SAMPLE] Draft project hero image" },
    disciplines: ["photography"],
    categoryIds: ["pcat-corporate"],
    collectionIds: [],
    seriesOrder: null,
    client: null,
    year: 2026,
    location: null,
    servicesProvided: [],
    equipmentUsed: [],
    tags: [],
    collaborators: [],
    story:
      "This project exists only to verify that draft projects are excluded from the public Portfolio hub and detail routes.",
    objective: null,
    strategy: null,
    challenges: null,
    solution: null,
    process: null,
    deliverables: [],
    results: null,
    awards: [],
    publications: [],
    gallery: [],
    behindTheScenesGallery: [],
    beforeAfterGallery: [],
    videos: [],
    downloadableAssets: [],
    testimonialIds: [],
    relatedProjectIds: [],
    relatedWorkshopIds: [],
    isPasswordProtected: true,
    seo: { metaTitle: null, metaDescription: null, ogImageUrl: null, canonicalUrl: null },
  },
];
