-- Ordift Studios — Member Number system (2026-07-28)
--
-- Replaces the flat, staff-only "Staff Number" (migration 0017) with a
-- configurable, platform-wide identity-numbering system, per explicit
-- instruction. Two new tables:
--
--   1. member_number_classifications — a Super-Admin-managed lookup
--      (same shape as operational_titles/engagement_types/grades):
--      each row defines one personnel category (Permanent Staff,
--      Intern, Client, Model, ... and any future category — Speaker,
--      Sponsor, etc. — created entirely from the admin UI, no code
--      change required), its display prefix ('' for Permanent Staff,
--      'IN' for Intern, ...), digit padding, and a configurable
--      starting number. Classification is explicitly assigned per
--      person — never derived/guessed from Role, Engagement Type, or
--      Operational Title, per explicit instruction ("Operational
--      Titles... should never determine or modify the Member Number").
--
--   2. member_numbers — an append-only ledger, not a single mutable
--      field: exactly one row per profile has status='active' at a
--      time (enforced by the partial unique index below), and every
--      prior number stays in the table as status='archived' with an
--      archived_at timestamp. This is the mechanism behind the
--      required lifecycle rule: a Member Number changes ONLY when a
--      person's classification changes (Intern → Permanent Staff), and
--      the old number is retained for history/audit, never deleted or
--      reused. Changing an Operational Title, Department, Grade, or
--      permissions must never touch this table.
--
-- profiles.member_number is a denormalized cache of the current active
-- row's formatted_number — kept in sync transactionally by application
-- code (src/lib/portal/memberNumbers.ts) — so every read site (Quick
-- Card, /admin/users, etc.) can display it with a plain profiles query
-- instead of a join, while member_numbers stays the source of truth
-- for history.
--
-- Numbers are generated by reusing next_record_sequence() (migration
-- 0013) — no new counter mechanism — keyed by an internal, never-
-- displayed "member:<slug>" prefix with a fixed year of 0 (never a
-- real calendar year) so each classification's counter never resets
-- and, unlike the visible prefix, is stable even if an admin later
-- edits the classification's display prefix or name. A new
-- seed_record_sequence() function lets a classification's counter
-- start from a configured number other than 1, without granting
-- direct table access to record_sequences (which stays service-role-
-- only internal plumbing, per 0013's own design note) — it's a thin
-- SECURITY DEFINER wrapper, same shape as next_record_sequence()
-- itself, and is a no-op (ON CONFLICT DO NOTHING) if that counter has
-- already been used, so it can never corrupt an in-progress sequence.
--
-- staff_details.staff_number (0017) is dropped: it was never assigned
-- to any real production account (only QA test accounts, all cleaned
-- up), so there is nothing to migrate, and keeping two parallel
-- "personal ID number" fields would contradict the explicit goal of
-- "one consistent identification system across the platform."

begin;

-- ============================================================
-- member_number_classifications
-- ============================================================
create table public.member_number_classifications (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) default public.ordift_studios_business_id(),
  slug text not null,
  name text not null,
  prefix text not null default '',
  number_padding int not null default 4 check (number_padding between 1 and 10),
  starting_number int not null default 1 check (starting_number >= 1),
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, slug),
  unique (business_id, prefix)
);

alter table public.member_number_classifications enable row level security;

create policy "member_number_classifications: admin read" on public.member_number_classifications
  for select
  to authenticated
  using ((select private.has_role('admin')) or (select private.is_super_admin()));

create policy "member_number_classifications: super_admin manages" on public.member_number_classifications
  for all
  to authenticated
  using ((select private.is_super_admin()))
  with check ((select private.is_super_admin()));

grant select, insert, update, delete on public.member_number_classifications to authenticated;
grant select, insert, update, delete on public.member_number_classifications to service_role;

create trigger member_number_classifications_set_updated_at
  before update on public.member_number_classifications
  for each row execute function public.set_updated_at();

-- ============================================================
-- member_numbers — append-only ledger, one active row per profile
-- ============================================================
create table public.member_numbers (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) default public.ordift_studios_business_id(),
  profile_id uuid not null references public.profiles (id) on delete cascade,
  classification_id uuid not null references public.member_number_classifications (id),
  formatted_number text not null,
  sequence_value int not null,
  status text not null default 'active' check (status in ('active', 'archived')),
  assigned_at timestamptz not null default now(),
  archived_at timestamptz,
  unique (business_id, formatted_number)
);

-- The actual lifecycle enforcement: at most one 'active' row per
-- profile at any time. Reclassifying someone is: archive the current
-- active row (status='archived', archived_at=now()), then insert a new
-- active row — never an update-in-place of the classification on an
-- existing row, so the old number is preserved verbatim.
create unique index member_numbers_one_active_per_profile
  on public.member_numbers (profile_id)
  where status = 'active';

create index member_numbers_profile_id_idx on public.member_numbers (profile_id);

alter table public.member_numbers enable row level security;

-- Not confidential like Grade — a Member Number is meant to be an
-- at-a-glance identifier, not sensitive data. Read own + staff/admin
-- read all, matching the general pattern used on profiles/enquiries.
-- No insert/update/delete policy for `authenticated` at all: every
-- assignment/reclassification goes through service-role application
-- code (src/lib/portal/memberNumbers.ts), never a direct authenticated
-- write, so the archive-then-insert invariant above can't be bypassed.
create policy "member_numbers: read own or staff" on public.member_numbers
  for select
  to authenticated
  using ((select auth.uid()) = profile_id or (select private.is_staff_or_admin()));

grant select on public.member_numbers to authenticated;
grant select, insert, update, delete on public.member_numbers to service_role;

-- ============================================================
-- profiles — denormalized current-number cache
-- ============================================================
alter table public.profiles
  add column if not exists member_number text unique;

comment on column public.profiles.member_number is
  'Denormalized cache of the current active row in public.member_numbers — source of truth is that table, not this column. Kept in sync transactionally by src/lib/portal/memberNumbers.ts.';

-- ============================================================
-- seed_record_sequence() — lets a classification's counter start from
-- a configured number. See header note above for why this exists
-- instead of granting direct record_sequences access.
-- ============================================================
create or replace function public.seed_record_sequence(p_prefix text, p_year integer, p_start_at integer)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.record_sequences (prefix, year, last_value)
  values (p_prefix, p_year, greatest(p_start_at - 1, 0))
  on conflict (prefix, year) do nothing;
end;
$$;

revoke all on function public.seed_record_sequence(text, integer, integer) from public;
revoke all on function public.seed_record_sequence(text, integer, integer) from anon;
revoke all on function public.seed_record_sequence(text, integer, integer) from authenticated;
grant execute on function public.seed_record_sequence(text, integer, integer) to service_role;

-- ============================================================
-- Retire the old staff-only numbering field (0017) — see header note.
-- ============================================================
alter table public.staff_details drop column if exists staff_number;

commit;
